<?xml version="1.0"?>
<robot name="bmt_walker" xmlns:xacro="http://ros.org/wiki/xacro">

  <!--Properties-->
  <!--All units in m-kg-s-radians unit system -->
  <xacro:property name="M_PI" value="3.1415926535897931" />
  <xacro:property name="M_PI_2" value="1.570796327" />

  <!-- Robot's Base Size -->
  <xacro:property name="base_x_size" value="0.74" />
  <xacro:property name="base_y_size" value="0.66" />
	<xacro:property name="base_z_size" value="1.15" />

  <!-- Wheel Properties -->
  <xacro:property name="wheel_vertical_offset" value="0.015" />
  <xacro:property name="wheel_length" value="0.045" />
	<xacro:property name="wheel_radius" value="0.0825" />

	<!-- Caster wheel properties-->
	<xacro:property name="caster_length" value="0.020" />
	<xacro:property name="caster_radius" value="0.032" />
	<xacro:property name="caster_z_offset" value="-0.05325" />
	<xacro:property name="caster_y_offset" value="0.159" />
	<xacro:property name="caster_x_offset" value="0.6315" />
	<xacro:property name="caster_mass" value="0.5"/>

	<!-- base_footprint is a fictitious link(frame) that is on the ground right below base_link origin -->
	<link name="base_footprint" >
		<inertial>
			<mass value="0.0001" />
     	<origin xyz="0 0 0" />
     	<inertia ixx="0.0001" ixy="0.0" ixz="0.0" iyy="0.0001" iyz="0.0" izz="0.0001" />
    </inertial>
  </link>
	<joint name="base_footprint_joint" type="fixed">
		<origin xyz="0 0 ${wheel_vertical_offset - wheel_radius}" rpy="0 0 0" />
		<parent link="base_link" />
		<child link="base_footprint" />
	</joint>
	<gazebo reference="base_footprint">
    <turnGravityOff>false</turnGravityOff>
	</gazebo>

	<!-- Base link is the center of rotation of the robot -->
	<link name="base_link">
		<inertial>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <mass value="23.3" />
      <inertia ixx="0.807" ixy="0" ixz="0" iyy="0.807" iyz="0" izz="0.807" />
    </inertial>
    <visual>
      <origin xyz="0 0 0" rpy="0 0 ${M_PI}" />
      <geometry>
        <mesh filename="package://bmt_sw_description/meshes/base_link_nowheels.STL" />
      </geometry>
      <material name="">
        <color rgba="0.898039215686275 0.917647058823529 0.929411764705882 1" />
      </material>
    </visual>
    <collision>
      <!--origin xyz="${base_x_size/2} 0 ${base_z_size/4}" rpy="0 0 0" /-->
	  <origin xyz="0 0 0" rpy="0 0 ${M_PI}" />
      <geometry>
        <mesh filename="package://bmt_sw_description/meshes/base_link_nowheels.STL" />
      </geometry>
    </collision>
  </link>
	<gazebo reference="base_link">
    <material>Gazebo/White</material>
    <turnGravityOff>false</turnGravityOff>
	</gazebo>

  <!--Left wheel-->
  <link name="left_wheel">
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <mass value="2.4" />
      <inertia ixx="0.00952875" ixy="0" ixz="0" iyy="0.00952875" iyz="0" izz="0.0081675" />
    </inertial>
    <visual>
      <origin xyz="0 0 0" rpy="-${M_PI_2} ${M_PI_2} 0" />
      <geometry>
        <mesh filename="package://bmt_sw_description/meshes/left_wheel.STL" />
      </geometry>
      <material name="">
        <color rgba="0.792156862745098 0.819607843137255 0.933333333333333 1" />
      </material>
    </visual>
    <collision>
      <origin xyz="0 ${wheel_length+0.01} 0" rpy="-${M_PI_2} ${M_PI_2} 0" />
      <geometry>
        <!--mesh filename="package://bmt_sw_description/meshes/left_wheel.STL" /-->
				<cylinder length="${wheel_length}" radius="${wheel_radius}"/>
      </geometry>
    </collision>
  </link>
  <gazebo reference="left_wheel">
		<mu1 value="1.0"/>
		<mu2 value="1.0"/>
		<kp value="10000000.0" />
		<kd value="1.0" />
		<fdir1 value="1 0 0"/>
		<material>Gazebo/Grey</material>
		<turnGravityOff>false</turnGravityOff>
	</gazebo>
  <joint name="left_wheel_joint" type="continuous">
    <parent link="base_link" />
    <child link="left_wheel" />
    <origin xyz="0 0.285 0" rpy="0 0 0" />
    <axis xyz="0 1 0" />
    <limit effort="100" velocity="100"/>
    <joint_properties damping="0.0" friction="0.5"/>
  </joint>
	<transmission name="left_wheel_trans" type="SimpleTransmission">
			<type>transmission_interface/SimpleTransmission</type>
			<joint name="left_wheel_joint"/>
			<actuator name="left_wheel_motor">
				<hardwareInterface>EffortJointInterface</hardwareInterface>
				<mechanicalReduction>1</mechanicalReduction>
			</actuator>
	</transmission>

	<!--Right wheel-->
  <link name="right_wheel">
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <mass value="2.4" />
      <inertia ixx="0.00952875" ixy="0" ixz="0" iyy="0.00952875" iyz="0" izz="0.0081675" />
    </inertial>
    <visual>
      <origin xyz="0 0 0" rpy="-${M_PI_2} ${M_PI_2} ${M_PI}" />
      <geometry>
        <mesh filename="package://bmt_sw_description/meshes/left_wheel.STL" />
      </geometry>
      <material name="">
        <color rgba="0.792156862745098 0.819607843137255 0.933333333333333 1" />
      </material>
    </visual>
    <collision>
      <origin xyz="0 -${wheel_length+0.01} 0" rpy="-${M_PI_2} ${M_PI_2} ${M_PI}" />
      <geometry>
        <!--mesh filename="package://bmt_sw_description/meshes/left_wheel.STL" /-->
				<cylinder length="${wheel_length}" radius="${wheel_radius}"/>
      </geometry>
    </collision>
  </link>
  <gazebo reference="right_wheel">
		<mu1 value="1.0"/>
		<mu2 value="1.0"/>
		<kp value="10000000.0" />
		<kd value="1.0" />
		<fdir1 value="1 0 0"/>
		<material>Gazebo/Grey</material>
		<turnGravityOff>false</turnGravityOff>
	</gazebo>
  <joint name="right_wheel_joint" type="continuous">
    <parent link="base_link" />
    <child link="right_wheel" />
    <origin xyz="0 -0.285 0" rpy="0 0 0" />
    <axis xyz="0 1 0" />
    <limit effort="100" velocity="100"/>
    <joint_properties damping="0.0" friction="0.5"/>
  </joint>
	<transmission name="right_wheel_trans" type="SimpleTransmission">
			<type>transmission_interface/SimpleTransmission</type>
			<joint name="right_wheel_joint"/>
			<actuator name="right_wheel_motor">
				<hardwareInterface>EffortJointInterface</hardwareInterface>
				<mechanicalReduction>1</mechanicalReduction>
			</actuator>
	</transmission>

	<!--Left caster wheel-->
	<link name="left_caster">
		<inertial>
		  	<mass value="${caster_mass}" />
		    <origin xyz="0 0 0" />
		    <inertia ixx="0.001" ixy="0.0" ixz="0.0" iyy="0.001" iyz="0.0" izz="0.001" />
    	</inertial>
		<visual>
			<origin xyz="0 0 0" rpy="${M_PI_2} 0 0" />
      <geometry>
				<cylinder length="${caster_length}" radius="${caster_radius}" />
      </geometry>
      <material name="DarkGray" />
    </visual>
    <collision>
			<origin xyz="0 0 0" rpy="${M_PI_2} 0 0" />
    	<geometry>
				<cylinder length="${caster_length}" radius="${caster_radius}" />
      </geometry>
    </collision>
	</link>
	<joint name="left_caster_joint" type="fixed">
		<parent link="base_link"/>
		<child link="left_caster"/>
		<origin xyz="${caster_x_offset} ${caster_y_offset} ${caster_z_offset}" rpy="0 0 0"/>
	</joint>
	<gazebo reference="left_caster">
		<turnGravityOff>false</turnGravityOff>
	</gazebo>

	<!-- Right caster wheel-->
	<link name="right_caster">
		<inertial>
    	<mass value="${caster_mass}" />
      <origin xyz="0 0 0" />
      <inertia ixx="0.001" ixy="0.0" ixz="0.0" iyy="0.001" iyz="0.0" izz="0.001" />
    </inertial>
		<visual>
      <origin xyz="0 0 0" rpy="${M_PI_2} 0 0" />
      <geometry>
				<cylinder length="${caster_length}" radius="${caster_radius}" />
      </geometry>
      <material name="DarkGray" />
    </visual>
    <collision>
			<origin xyz="0 0 0" rpy="${M_PI_2} 0 0" />
    	<geometry>
				<cylinder length="${caster_length}" radius="${caster_radius}" />
      </geometry>
    </collision>
	</link>
	<joint name="right_caster_joint" type="fixed">
		<parent link="base_link"/>
		<child link="right_caster"/>
		<origin xyz="${caster_x_offset} -${caster_y_offset} ${caster_z_offset}" rpy="0 0 0"/>
	</joint>
	<gazebo reference="right_caster">
		<turnGravityOff>false</turnGravityOff>
	</gazebo>

	<!-- Left force link-->
  <link name="left_force">
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <mass value="1.26336608136047" />
      <inertia
        ixx="0.00222782751505132"
        ixy="0"
        ixz="0"
        iyy="0.00235615491759392"
        iyz="0"
        izz="0.0001283274025426" />
    </inertial>
    <visual>
      <origin xyz="0 0 0.0381" rpy="0 0 ${M_PI}" />
      <geometry>
        <mesh filename="package://bmt_sw_description/meshes/left_force.STL" />
      </geometry>
      <material name="">
        <color rgba="0.792156862745098 0.819607843137255 0.933333333333333 1" />
      </material>
    </visual>
    <collision>
      <origin xyz="0 0 0.0381" rpy="0 0 ${M_PI}" />
      <geometry>
        <mesh filename="package://bmt_sw_description/meshes/left_force.STL" />
      </geometry>
    </collision>
  </link>
  <joint name="left_force_base" type="fixed">
    <origin xyz="-0.00175 0.29725 0.9025" rpy="0 0 0" />
    <parent link="base_link" />
    <child link="left_force" />
    <!--axis xyz="0 0 0" /-->
  </joint>

	<!--Right force link-->
  <link name="right_force">
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <mass value="1.26336608136047" />
      <inertia
        ixx="0.00222782751505132"
        ixy="0"
        ixz="0"
        iyy="0.00235615491759392"
        iyz="0"
        izz="0.0001283274025426" />
    </inertial>
    <visual>
      <origin xyz="0 0 0.0381" rpy="0 0 ${M_PI}" />
      <geometry>
        <mesh filename="package://bmt_sw_description/meshes/left_force.STL" />
      </geometry>
      <material name="">
        <color rgba="0.792156862745098 0.819607843137255 0.933333333333333 1" />
      </material>
    </visual>
    <collision>
      <origin xyz="0 0 0.0381" rpy="0 0 ${M_PI}" />
      <geometry>
        <mesh filename="package://bmt_sw_description/meshes/left_force.STL" />
      </geometry>
    </collision>
  </link>
  <joint name="right_force_base" type="fixed">
    <origin xyz="-0.00175 -0.29725 0.9025" rpy="0 0 0" />
    <parent link="base_link" />
    <child link="right_force" />
    <!--axis xyz="0 0 0" /-->
  </joint>

	<!--Deck0 link-->
  <link name="deck_0">
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <mass value="1.4" />
      <inertia ixx="0" ixy="0" ixz="0" iyy="0" iyz="0" izz="0" />
    </inertial>
    <visual>
      <origin xyz="0 0 0.016" rpy="${M_PI_2} 0 ${M_PI_2}" />
      <geometry>
        <mesh filename="package://bmt_sw_description/meshes/deck_0.STL" />
      </geometry>
      <material name="">
        <color rgba="0.792156862745098 0.819607843137255 0.933333333333333 1" />
      </material>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="${M_PI_2} 0 ${M_PI_2}" />
      <geometry>
        <mesh filename="package://bmt_sw_description/meshes/deck_0.STL" />
      </geometry>
    </collision>
  </link>
  <joint name="deck_0_base" type="fixed">
    <origin xyz="0.47516 0 0.027" rpy="0 0 0" />
    <parent link="base_link" />
    <child link="deck_0" />
    <axis xyz="0 0 0" />
  </joint>

	<!--Deck1 link-->
  <link name="deck_1">
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <mass value="11.57148011871309" />
      <inertia ixx="0" ixy="0" ixz="0" iyy="0" iyz="0" izz="0" />
    </inertial>
    <visual>
      <origin xyz="0 0 -0.207" rpy="${M_PI} 0 -${M_PI_2}" />
      <geometry>
        <mesh filename="package://bmt_sw_description/meshes/deck_1.STL" />
      </geometry>
      <material name="">
        <color rgba="1 1 1 1" />
      </material>
    </visual>
    <collision>
      <origin xyz="0 0 -0.207" rpy="${M_PI} 0 ${M_PI_2}" />
      <geometry>
        <mesh filename="package://bmt_sw_description/meshes/deck_1.STL" />
      </geometry>
    </collision>
  </link>
  <joint name="deck_1_base" type="fixed">
    <origin xyz="0 0 0.213" rpy="0 0 0" />
    <parent link="deck_0" />
    <child link="deck_1" />
    <axis xyz="0 0 0" />
  </joint>

	<!-- Differential drive controller  -->
  <gazebo>
    <plugin name="differential_drive_controller" filename="libgazebo_ros_diff_drive.so">
      <legacyMode>true</legacyMode>
      <rosDebugLevel>Debug</rosDebugLevel>
      <publishWheelTF>true</publishWheelTF>
      <robotNamespace>/</robotNamespace>
      <publishTf>1</publishTf>
      <publishWheelJointState>false</publishWheelJointState>
      <publishOdomTF>true</publishOdomTF>
      <alwaysOn>true</alwaysOn>
      <updateRate>100.0</updateRate>
      <leftJoint>left_wheel_joint</leftJoint>
	  <rightJoint>right_wheel_joint</rightJoint>
      <wheelSeparation>${base_y_size}</wheelSeparation>
      <wheelDiameter>${2*wheel_radius}</wheelDiameter>
      <broadcastTF>1</broadcastTF>
      <wheelTorque>30</wheelTorque>
      <wheelAcceleration>1.8</wheelAcceleration>
      <commandTopic>cmd_vel</commandTopic>
      <odometryFrame>odom</odometryFrame>
      <odometryTopic>odom</odometryTopic>
      <robotBaseFrame>base_footprint</robotBaseFrame>
    </plugin>
	</gazebo>
</robot>
